development:
  adapter: postgresql
  encoding: utf8
  database: latest_event_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: latest_event_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: latest_event_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST